// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using JeudanMadbestilling.Data;

namespace JeudanMadbestilling.Migrations
{
    [DbContext(typeof(MvcMadMenuContext))]
    [Migration("20191211144032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcMadMenu.Models.MadMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Dato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Med_Hjem_Køkken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uge")
                        .HasColumnType("int");

                    b.Property<string>("UgeNavn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.ToTable("Madmenu");
                });

            modelBuilder.Entity("MvcMadMenu.Models.Madbestillings", b =>
                {
                    b.Property<int>("MadbestillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AntalBestillinger")
                        .HasColumnType("int");

                    b.Property<string>("BestilingsType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BestillingsDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bruger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MenuDato")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("MenuTekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MadbestillingId");

                    b.HasIndex("MenuId");

                    b.ToTable("Madbestillings");
                });

            modelBuilder.Entity("MvcMadMenu.Models.Madbestillings", b =>
                {
                    b.HasOne("MvcMadMenu.Models.MadMenu", "Menu")
                        .WithMany("Madbestillinger")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
